version: "3"
services:
  app:
    container_name: "app"
    volumes:
      - ./app:/app
    tty: true
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
  
  #youtube動画の英語字幕取得用のサービス
  get-subtitle-service:
    build: ./getSubtitles
    restart: always
    tty: true
    ports:
      - 5001:5001
    environment:
      TZ: Asia/Tokyo
    volumes:
      - "./getSubtitles/:/projects"
    command: python /projects/app.py

  #gRPCでyoutube動画の英語字幕取得用のサービス
  grpc-subtitle-service:
    build: ./grpcSubtitles
    restart: always
    tty: true
    ports:
      - 5002:5002
    environment:
      TZ: Asia/Tokyo
    volumes:
      - "./grpcSubtitles/:/projects"
    command: python /projects/server.py
  
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./db/mysql_data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ecc
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci