POST http://localhost:3000/users/update/2
Content-Type: application/json

{
    "id":2, "name": "更新済み"
}

###

GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "test二郎", "mail": "test2@ecc.ac.jp", "password": "password1234"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "mail": "test2@ecc.ac.jp", "password": "password1234"
}

###
POST http://localhost:3000/users/update
Content-Type: application/json

{
    "mail": "test1@ecc.ac.jp", "password": "password1234", "name": "変更した"
}

###

POST http://localhost:3000/users/delete
Content-Type: application/json

{
    "mail": "test1@ecc.ac.jp", "password": "password1234" 
}

###

GET http://localhost:3000/users/authenticate
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGVjYy5hYy5qcCIsImV4cCI6MTY2MDAyMTY4MSwiaWF0IjoiMjAyMi0wOC0wOVQwNDowODowMS40NzE2MTkxMDJaIiwibmFtZSI6InRlc3Tkuozpg44iLCJzdWIiOjJ9.Bv6Fip9-TTw55oZLVX9eJWd2cLlD3eLvbbaSb1DC2nQ